---
- name: Install MySQL 8.0
  hosts: servers
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL 8.0
      apt:
        name: mysql-server-8.0
        state: present
