---
- name: Install PHP 7.4
  hosts: servers
  become: yes

  tasks:

    - name: Install PHP repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP 7.4
      apt:
        name: php7.4
        state: present
